# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cc9900e5b4e6c0abfdcbc69e0459bad98b79661bf24fff8cc8783e79d98591af87dda4d1270379b63d7c5f0f0a9010560b8590a19395db7444e0e68a8a835d75

test:
  secret_key_base: 1cdc1b0246420af9aa3edc89e7b8a6e62bfdebfc65dd6765f49976cc9d5add32748c6d425d7192645faae6d99062542750fd934814d1a96b61f834b0f7f3c0db

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
